### PR TITLE
signing_key, not secure_key.

### PR DESCRIPTION
**Pull request by sdebacker**

### CODE REVIEW

**Comment by weotch** [comment]
Thanks!

**Comment by weotch** [comment]
Tagges as 4.2.1

**Comment by sdebacker** [comment]
Nice.
But I don't know why I have a 404 error in production on a forge server.
My url is like this : http://example.com/uploads/news/test-150x150-resize.jpg?token=bafa128ddc465f289a7ff6ae9822584c

**Comment by weotch** [comment]
Huh, so it's working locally, but not on prod? Can you think of a reason that the [basename()](https://github.com/BKWLD/croppa/blob/master/src/Bkwld/Croppa/URL.php#L114) of the image might be returned differently between environments and different between when the URL is generated in the markup and when Croppa handles the request to create the image?

Maybe the token is being stripped out by some mod_rewrite setting or some middleware?

**Comment by sdebacker** [comment]
Yes it’s working locally (Apache/2.4.10 and PHP 5.6.7 on mac os x) but not on laravel forge (nginx). I will investigate more on this when I find some time.

**Pull request merged**
