### PR TITLE
Fix crop already exists error

### PR DESCRIPTION
**Pull request by eliysha**
Fixes https://github.com/BKWLD/croppa/issues/159 and https://github.com/BKWLD/croppa/issues/137

### CODE REVIEW

**Comment by weotch** [comment]
The thing is, Croppa _shouldn't_ run if the crop exists on a local system.  Instead, the web server should have interceeded and served the image directly from the disk before Laravel boots.  The advantage of Croppa over some other cropping libraries is that after the original crop is made, PHP should not have to boot to resolve the path to the image.  I think this PR masks that issue and your server will be doing more work than it's supposed to.

**Comment by sevenpointsix** [comment]
I believe that this PR is valid. It certainly fixed the same issue for me (using local source files and crops). I take @weotch's point about Croppa not running if the crop exists on a local file system, but I believe that this is what the PR implements; if the crop exists, just return a path to it so that the direct file is served, rather than asking Croppa to do any work.

**Comment by umair321** [comment]
Getting this issue in L5.6 with Croppa version 4.7

**Comment by jordanade** [comment]
> I believe that this PR is valid. It certainly fixed the same issue for me (using local source files and crops). I take @weotch's point about Croppa not running if the crop exists on a local file system, but I believe that this is what the PR implements; if the crop exists, just return a path to it so that the direct file is served, rather than asking Croppa to do any work.

Well the expected behavior is for the web server to completely bypass all of PHP, not just Croppa. I too get these errors sporadically (local crops, S3 originals) and I can't figure out what's going on.

**Comment by stefnats** [comment]
Maybe a quick hint, sometimes we have traffic peaks and i think this could cause the error.

Two requests at the same time and "PHP redirects traffic to croppa": first one creates the crop and second one sees that the crop already exists and throws the error. Is this a possible scenario as i think it is?
Once the crop exists at "check time", it doesn't throw an error anymore. It's hard to catch actually, i never had this issue but sometimes it shows up in sentry.

Edit: I'm using local crops and local sources

**Comment by jordanade** [comment]
> Maybe a quick hint, sometimes we have traffic peaks and i think this could cause the error.

Even on our no-traffic QA environment I'm seeing these errors. But only sporadically.

**Comment by weotch** [comment]
@stefnats I think you may be on the right track here ... lets say you had a page with the same image with the same crops rendered on it 5 times.  On an initial request of this page, the crop would not exist.  Lets say there were 5 http server threads handling these requests.  If the requests all hit at the same time, all 5 would try to generate the image and save it to disk.  One of them would finish first and then the other 4 would throw `Crop already exists` exceptions.   I feel like this is a valid use case and **IS** a reason that I should make this condition _not_ fatally error.  It should just silently return the image response. 

However, I think the fix should be a change to [`writeCrop`](https://github.com/BKWLD/croppa/blob/master/src/Bkwld/Croppa/Storage.php#L172-L189) where it just `return`s rather than throwing an `Exception`.

**Comment by stefnats** [comment]
@weotch yes, don't make it fatal. i would second that.
Maybe you could just make it fatal if the last_modified of the crop is older than a certain threshold, let's say 5 seconds.

**Comment by weotch** [comment]
Closing this in favor of #174

**Comment by weotch** [comment]
Also, if anyone wants to be added as a maintainer, lemme know.  I'm not doing so much Laravel anymore (thus the massive delay in responding to this, sorry for that).

**Pull request closed without merging**
