### PR TITLE
Laravel 5 service provider with backwards compatibility

### PR DESCRIPTION
**Pull request by swiggles**
Not fully tested yet, but the provider loads and the Facade works, unless there's any code other than the service providers, should be all good

### CODE REVIEW

**Comment by weotch** [comment]
Yeah, maybe a convention will arise in the future for env configs in packages, but your approach works for me and is nicely backwards compatible too.

**Comment by swiggles** [comment]
Well this could be useful http://laravel.io/forum/01-16-2015-laravel-5-package-configuration.

Also could you do a new release please.

**Comment by weotch** [comment]
Done, thanks for the contribution!

**Comment by josephilipraja** [comment]
@weotch Am still having the same error, tried `composer update` (with `"bkwld/croppa": "~4"`).
And I don't see a release with this fix, please do it..

BTW, thanks for the cool package :)

**Comment by weotch** [comment]
I just tagged a [4.4.0 relaease](https://github.com/BKWLD/croppa/releases/tag/4.4.0) which contains the fix for #119 which I think will fix your issue

**Pull request merged**
