### PR TITLE
Laravel 6 compatibility

### PR DESCRIPTION
**Pull request by sdebacker**

### CODE REVIEW

**Comment by weotch** [comment]
Do you have any experience with those Travis errors?  It seems to be always using the wrong version of phpunit for the PHP version being tested...

**Comment by sdebacker** [comment]
No, I don’t understand. We can also change the two failing tests so it passes with phpunit 7.5, but here too, I couldn’t see what to do. Perhaps you will better understand?

**Comment by halloei** [comment]
Among changes that might be needed to support Laravel 6, you did a lot of other stuff, e.g. formatting.
However, I'm also waiting for Laravel 6 support. This is the only package of mine which is missing this.

**Comment by dexcell** [comment]
Any news?

**Comment by weotch** [comment]
I merged #183, which I think deprecates this issue

**Pull request closed without merging**
