### PR TITLE
Add a configuration option to disable the default routing

### PR DESCRIPTION
**Pull request by xel1045**
This allows custom routing for Croppa.

### CODE REVIEW

**Comment by weotch** [comment]
Tell me about your use case for this.  I'm cool with the change, just wondering about it.

Also, another i'm-curious thing: what do you have installed that is enforcing all those whitespace changes?

**Comment by xel1045** [comment]
My use case is the following: I want to be able to define my own route for croppa instead of using the one provided in the service provider. This allows for greater flexibility and prevents croppa from setting a route which I may not want to use.

For whitespace stripping, I use phpStorm. It removes useless spaces on save.

**Comment by weotch** [comment]
Why do you need your own route?  Can you show me an example?  I'm wondering if there is an opportunity for me to improve the default route regex.

Or is your use case very unique to your app?

**Comment by xel1045** [comment]
This bug is kinda related with #69. I would like to rapidly fix the fact that Croppa answers to requests that are not defined in the source path.

Here’s an example of how we'd use it:
```
Route::get('storage/images/{path}', function() {
    // Invoke croppa
})->where('path', 'croppa-pattern');
```

**Comment by weotch** [comment]
It sounds like if I finished #13 it would solve for your use case and might make the PR unnecessary.

**Comment by xel1045** [comment]
Yes.

**Comment by weotch** [comment]
Ok, check out #13.  You would change your src_dir config to be `public_path().'/storage/images/'` and I believe it should work as you intend.  Let me know how it goes for you.

**Comment by xel1045** [comment]
Thanks, I'll try this on monday. :)

**Comment by weotch** [comment]
Btw, just tagged those commits as 3.5.0

**Pull request closed without merging**
